name: Documentation build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install .
    - name: Install software
      run: |
        pip install .
    - name: Build docs
      run: |
        cd docs
        make html
    - name: Upload docs
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/_build/html
    - name: Publish docs to Github Pages
      if: startsWith(github.event.ref, 'refs/tags')
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: 'docs/_build/html' # The folder the action should deploy.
